python3 -m domainbed.scripts.few_shot_adapt_mnistm_after_WA \
    --data_dir=../data \
    --model_name resnet50 \
    --target_dataset VisDA \
    --num_classes 12 \
    --sweep_dir=./VisDA_sweep_diwa_adam \
    --output_dir=./VisDA_adam_diwa_synth2real_adam_10_shot \
    --weight_selection uniform \
    --opt_name Adam \
    --sam_rho 0.05 \
    --k_shot 10 \
    --steps 100
